# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: UQTestFuns
author: Damar Wicaksono

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  timeout: 300

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: uqtestfuns.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Sphinx-related settings
sphinx:
  extra_extensions:
    - 'sphinx.ext.autodoc'
    - 'sphinx.ext.napoleon'
    - 'sphinx.ext.intersphinx'
    - 'sphinx_proof'
    - 'sphinxcontrib.mermaid'
  config:
    html_static_path:
      - _static
    html_favicon: _static/favicon.ico
    html_theme_options:
      logo:
        image_light: _static/logo-light.png
        image_dark: _static/logo-dark.png
      repository_url: https://github.com/damar-wicaksono/uqtestfuns
      repository_branch: dev
      use_repository_button: true
      use_issues_button: true
